# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build and deploy the entire application
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

pool:
  vmImage: windows-latest

# ------------------------------------------------------------------------------------------------------------------------
trigger: none
 
parameters:
  - name: runDevSecOpsScan
    displayName: Run MS DevSecOps Scan
    type: boolean
    default: false
  - name: runPsRuleScan
    displayName: Run PSRule Bicep Scan
    type: boolean
    default: false
  - name: runGHAzDOScan
    displayName: Run GHAS Scan
    type: boolean
    default: false

# ------------------------------------------------------------------------------------------------------------------------
variables:
  # Lyle's variables
  # TODO: put the variables into a variable group so they can be updated easily
  azureSubscription: 'Lyle Luppes Sandbox'
  webAppName: 'lll-webapp1-webapp'
  apiAppName: 'lll-webapp1-api'
  apiAppAPIMName: 'lll-webapp1-apim'
  organizationName: 'LyleLuppes'
  adminEmail: 'LyleLuppes@microsoft.com'
  resourceGroupName: 'rg_webapp1_dev'

  # Scott's variables
  # azureSubscription: 'Demo Account'
  # apiAppName: 'rutzscodev-demo-webapp-api-auth-api-ci'
  # apiAppAPIMName: 'rutzsco-demo-webapp-api-auth-api-ci'
  # organizationName: 'scrutz'
  # adminEmail: 'scrutz@microsoft.com'
  # resourceGroupName: 'rutzscodev-demo-webapp-api-auth-api-ci'

  # Global variables
  webAppSourcePath: '/services/Demo.WebUI'
  webAppPackageName: 'Demo.WebUI.zip'
  apiSourcePath: '/services/Demo.API'
  apiPackageName: 'Demo.API.zip'
  region: 'East US'
  workingDirectoryCode: '/services/Demo.WebUI'
  workingDirectoryInfra: '/infra/'
  
stages:
# ------------------------------------------------------------------------------------------------------------------------
- template: pipes/build-infra-deploy-pipe.yml
  parameters:
    apiRootDirectory: ${{ variables.apiSourcePath }}
    webAppRootDirectory: ${{ variables.apiSourcePath }}
    azureSubscription: ${{ variables.azureSubscription }}
    webAppName:  ${{ variables.webAppName }}
    apiAppName:  ${{ variables.apiAppName }}
    apiAppAPIMName:  ${{ variables.apiAppAPIMName }}
    organizationName:  ${{ variables.organizationName }}
    adminEmail:  ${{ variables.adminEmail }}
    resourceGroupName:  ${{ variables.resourceGroupName }}
    region: ${{ variables.region }}
    apiPackageName: ${{ variables.apiPackageName }}
    apiSourcePath: ${{ variables.apiSourcePath }}
    webAppPackageName: ${{ variables.webAppPackageName }}
    webAppSourcePath: ${{ variables.webAppSourcePath }}
    runDevSecOpsScan: ${{ parameters.runDevSecOpsScan }}
    runPsRuleScan: ${{ parameters.runPsRuleScan }}
    runGHAzDOScan: ${{ parameters.runGHAzDOScan }}
    workingDirectoryCode: ${{ variables.workingDirectoryCode }}
    workingDirectoryInfra: ${{ variables.workingDirectoryInfra }}
