# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build and deploy the entire application
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

pool:
  vmImage: windows-latest

# ------------------------------------------------------------------------------------------------------------------------
trigger: none
 
parameters:
  - name: createInfra
    displayName: Create Infra
    type: boolean
    default: true
  - name: buildDeployApps
    displayName: Build and Deploy Apps
    type: boolean
    default: true
  - name: runDevSecOpsScan
    displayName: Run MS DevSecOps Scan
    type: boolean
    default: false
  - name: runGHAzDOScan
    displayName: Run GHAS Scan
    type: boolean
    default: false
  - name: runPlaywright
    displayName: Run Playwright Tests
    type: boolean
    default: false

# ------------------------------------------------------------------------------------------------------------------------
variables:
  # Lyle's variables
  - group: 'Playwright'
    # Group contains these variables:
    # azureSubscription: 'yourSubscriptionName'
    # webAppName: 'xxx-playwright-web'
    # apiAppName: 'xxx-playwright-api'
    # apiAppAPIMName: 'xxx-playwright-apim'
    # organizationName: 'yourOrgName'
    # adminEmail: 'you@yourDomain.com'
    # resourceGroupName: 'rg_playwright_testing'
    # region: 'East US'
    # adDomain: 'yourdomain.onmicrosoft.com'
    # adTenantId: 'someGuid'
    # adClientId: 'someGuid'
    # webAPIScope='api://xxxxxGUIDxxxxx/.default'
    # webAPIUrl='https://xxxxApimNamexxxx.azure-api.net/WeatherForecast'

  # Project Static variables
  - name: webSourcePath 
    value: 'services/Demo.WebUI'
  - name: apiSourcePath
    value:  'services/Demo.API'
  - name: webPackageName
    value:  'Demo.WebUI.zip'
  - name: apiPackageName
    value:  'Demo.API.zip'
  - name: webArtifactName
    value:  'WebApp'
  - name: apiArtifactName
    value:  'WebApi'
  - name: workingDirectoryCode
    value:  'services/'
  - name: workingDirectoryInfra
    value:  'infra/'
  
stages:
# ------------------------------------------------------------------------------------------------------------------------
- template: pipes/build-infra-deploy-pipe.yml
  parameters:
    createInfra: ${{ parameters.createInfra }}
    buildDeployApps: ${{ parameters.buildDeployApps }}
    runDevSecOpsScan: ${{ parameters.runDevSecOpsScan }}
    runGHAzDOScan: ${{ parameters.runGHAzDOScan }}

    organizationName:  ${{ variables.organizationName }}
    adminEmail:  ${{ variables.adminEmail }}
    resourceGroupName:  ${{ variables.resourceGroupName }}
    region: ${{ variables.region }}
    azureSubscription: ${{ variables.azureSubscription }}

    apiAppAPIMName:  ${{ variables.apiAppAPIMName }}
    webAPIScope:  ${{ variables.webAPIScope }}
    webAPIUrl:  ${{ variables.webAPIUrl }}

    webRootDirectory: ${{ variables.apiSourcePath }}
    apiRootDirectory: ${{ variables.apiSourcePath }}

    webAppName:  ${{ variables.webAppName }}
    apiAppName:  ${{ variables.apiAppName }}

    webPackageName: ${{ variables.webPackageName }}
    apiPackageName: ${{ variables.apiPackageName }}

    webSourcePath: ${{ variables.webSourcePath }}
    apiSourcePath: ${{ variables.apiSourcePath }}

    webArtifactName:  ${{ variables.webArtifactName }}
    apiArtifactName:  ${{ variables.apiArtifactName }}

    workingDirectoryCode: ${{ variables.workingDirectoryCode }}
    workingDirectoryInfra: ${{ variables.workingDirectoryInfra }}

    adDomain: ${{ variables.adDomain }}
    adTenantId: ${{ variables.adTenantId }}
    adClientId: ${{ variables.acClientId }}
