# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build and deploy the entire application
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

pool:
  vmImage: windows-latest

# ------------------------------------------------------------------------------------------------------------------------
trigger: none
 
parameters:
  - name: createInfra
    displayName: Create Infra
    type: boolean
    default: true
  - name: buildDeployApps
    displayName: Build and Deploy Apps
    type: boolean
    default: true
  - name: runDevSecOpsScan
    displayName: Run MS DevSecOps Scan
    type: boolean
    default: false
  - name: runGHAzDOScan
    displayName: Run GHAS Scan
    type: boolean
    default: false
  - name: runPlaywright
    displayName: Run Playwright Tests
    type: boolean
    default: false

# ------------------------------------------------------------------------------------------------------------------------
variables:
  # Lyle's variables
  # TODO: put the variables into a variable group so they can be updated easily
  azureSubscription: 'Lyle Luppes Sandbox'
  webAppName: 'lll-playwright-web'
  apiAppName: 'lll-playwright-api'
  apiAppAPIMName: 'lll-playwright-apim'
  organizationName: 'lyleluppes'
  adminEmail: 'lyleluppes@microsoft.com'
  resourceGroupName: 'rg_playwright_testing'

  # Scott's variables
  # azureSubscription: 'Demo Account'
  # apiAppName: 'rutzscodev-demo-webapp-api-auth-api-ci'
  # apiAppAPIMName: 'rutzsco-demo-webapp-api-auth-api-ci'
  # organizationName: 'scrutz'
  # adminEmail: 'scrutz@microsoft.com'
  # resourceGroupName: 'rutzscodev-demo-webapp-api-auth-api-ci'

  # Global variables
  webAppSourcePath: 'services/Demo.WebUI'
  webAppPackageName: 'Demo.WebUI.zip'
  apiSourcePath: 'services/Demo.API'
  apiPackageName: 'Demo.API.zip'
  region: 'East US'
  workingDirectoryCode: 'services/Demo.WebUI'
  workingDirectoryInfra: 'infra/arm/'
  
stages:
# ------------------------------------------------------------------------------------------------------------------------
- template: pipes/build-infra-deploy-pipe.yml
  parameters:
    createInfra: ${{ parameters.createInfra }}
    buildDeployApps: ${{ parameters.buildDeployApps }}
    runDevSecOpsScan: ${{ parameters.runDevSecOpsScan }}
    runGHAzDOScan: ${{ parameters.runGHAzDOScan }}

    apiRootDirectory: ${{ variables.apiSourcePath }}
    webAppRootDirectory: ${{ variables.apiSourcePath }}
    azureSubscription: ${{ variables.azureSubscription }}
    webAppName:  ${{ variables.webAppName }}
    apiAppName:  ${{ variables.apiAppName }}
    apiAppAPIMName:  ${{ variables.apiAppAPIMName }}
    organizationName:  ${{ variables.organizationName }}
    adminEmail:  ${{ variables.adminEmail }}
    resourceGroupName:  ${{ variables.resourceGroupName }}
    region: ${{ variables.region }}
    apiPackageName: ${{ variables.apiPackageName }}
    apiSourcePath: ${{ variables.apiSourcePath }}
    webAppPackageName: ${{ variables.webAppPackageName }}
    webAppSourcePath: ${{ variables.webAppSourcePath }}
    workingDirectoryCode: ${{ variables.workingDirectoryCode }}
    workingDirectoryInfra: ${{ variables.workingDirectoryInfra }}
