# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to run a Playwright test
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

pool:
  vmImage: ubuntu-latest

# ------------------------------------------------------------------------------------------------------------------------
trigger: none

stages:
# ------------------------------------------------------------------------------------------------------------------------
- template: pipes/run-playwright-pipe.yml
  parameters:
    pwVariableGroupName: 'Playwright'
    pwKVGroupName: 'PlaywrightSecrets'
    pwScriptPath: 'playwright'
