# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to run a Playwright test
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

pool:
  vmImage: ubuntu-latest

# ------------------------------------------------------------------------------------------------------------------------
trigger: none

parameters:
  - name: runPlaywright
    displayName: Run Playwright Tests
    type: boolean
    default: false

stages:
# ------------------------------------------------------------------------------------------------------------------------
  
- template: pipes/build-infra-deploy-pipe.yml
  parameters:
    variableGroupName: 'Playwright'
    keyVaultVariableGroupName: 'PlaywrightSecrets'
    environment: 'CI'
    baseTestingUrl: 'https://lll-playwright-web.azurewebsites.net/'
    testScriptPath: 'tests'
