# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to run a Playwright test
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

pool:
  vmImage: ubuntu-latest

# ------------------------------------------------------------------------------------------------------------------------
trigger: none

# parameters:
#   - name: runPlaywright
#     displayName: Run Playwright Tests
#     type: boolean
#     default: true

stages:
# ------------------------------------------------------------------------------------------------------------------------
- template: pipes/run-playwright-pipe.yml
  parameters:
    pwVariableGroupName: 'Playwright'
    pwKVGroupName: 'PlaywrightSecrets'
    pwScriptPath: 'playwright'
    #pwBaseUrl: 'https://lll-playwright-web.azurewebsites.net/'
