# ----------------------------------------------------------------------------------------------------
# Template to deploy the WebAPI and WebApp to Azure
# ----------------------------------------------------------------------------------------------------
parameters: 
- name: stageName
  default: 'CI'
- name: environment
  default: 'CI'
- name: azureSubscription
  default: ''
- name: webAppName
  default: ''
- name: webAppPackageName
  default: ''  
- name: apiAppName
  default: ''
- name: apiPackageName
  default: ''  

# ----------------------------------------------------------------------------------------------------
jobs:
- deployment: DeployApps
  displayName: Deploy Apps
  environment: ${{ parameters.environment }}

- job: DeployAppsJob
  displayName: Deploy Apps Job
  steps:
  - task: CmdLine@2
    inputs:
      script: |
        echo "stageName=${{ parameters.stageName }}"
        echo "environment=${{ parameters.environment }}"
        echo "azureSubscription=${{ parameters.azureSubscription }}"
        echo "webAppName=${{ parameters.webAppName }}"
        echo "webAppPackageName=${{ parameters.webAppPackageName }}"
        echo "apiAppName=${{ parameters.apiAppName }}"
        echo "apiPackageName=${{ parameters.apiPackageName }}"
        echo "Directory of Pipeline.Workspace:"
        dir  $(Pipeline.Workspace) /s
    displayName: 'Display Variables and Tree'
    continueOnError: true

  - task: AzureRmWebAppDeployment@4
    displayName: '1. Deploy API'
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      WebAppName: ${{ parameters.apiAppName }}
      package: '$(Pipeline.Workspace)/build/WebApi/${{ parameters.apiPackageName }}'
      AppSettings: ''

  - task: AzureRmWebAppDeployment@4
    displayName: '2. Deploy WebApp'
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      WebAppName: ${{ parameters.webAppName }}
      package: '$(Pipeline.Workspace)/build/WebApp/${{ parameters.webAppPackageName }}'
      AppSettings: ''