# ------------------------------------------------------------------------------------------------------------------------
# Pipe Template to build and deploy the entire application
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: buildConfiguration
  default: 'Release'
- name: apiRootDirectory
  default: ''
- name: webAppRootDirectory
  default: ''
- name: azureSubscription
  default: ''
- name: webAppName
  default: ''
- name: apiAppName
  default: ''
- name: apiAppAPIMName
  default: ''
- name: organizationName
  default: ''
- name: adminEmail
  default: ''
- name: resourceGroupName
  default: ''
- name: region
  default: ''
- name: apiPackageName
  default: ''
- name: apiSourcePath
  default: ''
- name: webAppPackageName
  default: ''
- name: webAppSourcePath
  default: ''
- name: runDevSecOpsScan
  default: 'false'
- name: runPsRuleScan
  default: 'false'
- name: runGHAzDOScan
  default: 'false'
- name: workingDirectoryCode
  default: 'src/myproject'
- name: workingDirectoryInfra
  default: '/infra/bicep'

stages:
# ------------------------------------------------------------------------------------------------------------------------
- stage: BuildApps
  displayName: Build Apps
  jobs:

  - ${{ if or(or(eq(lower(parameters.runDevSecOpsScan), 'true'), eq(lower(parameters.runPsRuleScan), 'true')), eq(lower(parameters.runGHAzDOScan), 'true')) }}:
    - template: templates/scan-code-template.yml
      parameters:
        environmentName: 'DEV'
        runDevSecOpsScan: ${{ parameters.runDevSecOpsScan }}
        runPsRuleScan: ${{ parameters.runPsRuleScan }}
        runGHAzDOScan: ${{ parameters.runGHAzDOScan }}
        workingDirectoryCode: ${{ parameters.workingDirectoryCode }}
        workingDirectoryInfra: ${{ parameters.workingDirectoryInfra }}

  - template: templates/build-webapi-template.yml
    parameters:
      buildConfiguration: 'Release'
      rootDirectory: ${{ parameters.apiSourcePath }}

  - template: templates/build-webapp-template.yml
    parameters:
      buildConfiguration: 'Release'
      rootDirectory: ${{ parameters.apiSourcePath }}

# ------------------------------------------------------------------------------------------------------------------------
- stage: CreateAzureInfra
  displayName: Create Azure Infra
  dependsOn: BuildApp
  condition: succeeded('BuildApp')
  jobs:
  - template: templates/create-infra-template.yml
    parameters:
      azureSubscription: ${{ parameters.azureSubscription }}
      webAppName:  ${{ parameters.webAppName }}
      apiAppName:  ${{ parameters.apiAppName }}
      apiAppAPIMName:  ${{ parameters.apiAppAPIMName }}
      organizationName:  ${{ parameters.organizationName }}
      adminEmail:  ${{ parameters.adminEmail }}
      resourceGroupName:  ${{ parameters.resourceGroupName }}
      region: ${{ parameters.region }}

# ------------------------------------------------------------------------------------------------------------------------
- stage: DeployApp
  displayName: Deploy App
  dependsOn: CreateInfra
  condition: succeeded('CreateInfra')
  jobs:
  - template: templates/deploy-apps-template.yml
    parameters:
      azureSubscription: ${{ parameters.azureSubscription }}
      webAppName:  ${{ parameters.webAppName }}
      webAppPackageName: ${{ parameters.webAppPackageName }}
      apiAppName:  ${{ parameters.apiAppName }}
      apiPackageName: ${{ parameters.apiPackageName }}
