# ------------------------------------------------------------------------------------------------------------------------
# Pipe Template to build and deploy the entire application
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: variableGroupName
  default: ''
- name: createInfra
  default: true
- name: buildDeployApps
  default: true
- name: runDevSecOpsScan
  default: 'false'
- name: runPsRuleScan
  default: 'false'
- name: runGHAzDOScan
  default: 'false'
- name: webSourcePath
  default: ''
- name: apiSourcePath
  default: ''
- name: webPackageName
  default: ''
- name: apiPackageName
  default: ''
- name: webArtifactName
  default: ''
- name: apiArtifactName
  default: ''
- name: workingDirectoryCode
  default: 'src/myproject'
- name: workingDirectoryInfra
  default: '/infra/bicep'
- name: buildConfiguration
  default: 'Release'

- name: runPlaywrightTests
  default: 'false'
- name: pwVariableGroupName
  default: ''
- name: pwKVGroupName
  default: ''
- name: pwScriptPath
  default: ''

stages:
# ------------------------------------------------------------------------------------------------------------------------
- stage: BuildApps
  displayName: Build Apps (${{ parameters.buildDeployApps }})
  jobs:
  - ${{ if or(or(eq(lower(parameters.runDevSecOpsScan), 'true'), eq(lower(parameters.runPsRuleScan), 'true')), eq(lower(parameters.runGHAzDOScan), 'true')) }}:
    - template: templates/scan-code-template.yml
      parameters:
        environmentName: 'DEV'
        runDevSecOpsScan: ${{ parameters.runDevSecOpsScan }}
        runPsRuleScan: ${{ parameters.runPsRuleScan }}
        runGHAzDOScan: ${{ parameters.runGHAzDOScan }}
        workingDirectoryCode: ${{ parameters.workingDirectoryCode }}
        workingDirectoryInfra: ${{ parameters.workingDirectoryInfra }}

  - template: templates/build-webapi-template.yml
    parameters:
      buildDeployApps: ${{ parameters.buildDeployApps }}
      buildConfiguration: 'Release'
      rootDirectory: ${{ parameters.apiSourcePath }}
      artifactName: ${{ parameters.apiArtifactName }} 

  - template: templates/build-webapp-template.yml
    parameters:
      buildDeployApps: ${{ parameters.buildDeployApps }}
      buildConfiguration: 'Release'
      rootDirectory: ${{ parameters.webSourcePath }}
      artifactName: ${{ parameters.webArtifactName }}

# ------------------------------------------------------------------------------------------------------------------------
- stage: CreateAzureInfra
  displayName: Create Infra (${{ parameters.createInfra }})
  dependsOn: BuildApps
  condition: succeeded('BuildApps')
  jobs:
  - template: templates/create-infra-template.yml
    parameters:
      variableGroupName: ${{ parameters.variableGroupName }}
      createInfra: ${{ parameters.createInfra }}

# ------------------------------------------------------------------------------------------------------------------------
- stage: DeployApp
  displayName: Deploy App (${{ parameters.buildDeployApps }})
  dependsOn: CreateAzureInfra
  condition: succeeded('CreateAzureInfra')
  jobs:
  - template: templates/deploy-apps-template.yml
    parameters:
      variableGroupName: ${{ parameters.variableGroupName }}
      buildDeployApps: ${{ parameters.buildDeployApps }}
      webPackageName: ${{ parameters.webPackageName }}
      apiPackageName: ${{ parameters.apiPackageName }}
      webArtifactName: ${{ parameters.webArtifactName }}
      apiArtifactName: ${{ parameters.apiArtifactName }} 

# ------------------------------------------------------------------------------------------------------------------------
- stage: SmokeTestApp
  displayName: Smoke Test App (${{ parameters.runPlaywrightTests }})
  dependsOn: DeployApp
  jobs:
  - ${{ if eq(lower(parameters.runPlaywrightTests), 'true') }}:
    - template: templates/playwright-template.yml
      parameters:
        pwVariableGroupName: ${{ parameters.pwVariableGroupName }}
        pwKVGroupName: ${{ parameters.pwKVGroupName }}
        pwScriptPath: ${{ parameters.pwScriptPath }}
