# ------------------------------------------------------------------------------------------------------------------------
# Pipe Template to build and deploy the entire application
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: variableGroupName
  default: ''

- name: createInfra
  default: true
- name: buildDeployApps
  default: true
- name: runDevSecOpsScan
  default: 'false'
- name: runPsRuleScan
  default: 'false'
- name: runGHAzDOScan
  default: 'false'

- name: buildConfiguration
  default: 'Release'

- name: webSourcePath
  default: ''
- name: apiSourcePath
  default: ''

- name: webPackageName
  default: ''
- name: apiPackageName
  default: ''

- name: webArtifactName
  default: ''
- name: apiArtifactName
  default: ''

- name: workingDirectoryCode
  default: 'src/myproject'
- name: workingDirectoryInfra
  default: '/infra/bicep'

# From VG:
# - name: adminEmail
#   default: ''
# - name: adDomain
#   default: ''
# - name: adTenantId
#   default: ''
# - name: adClientId
#   default: ''
# - name: apiAppName
#   default: ''
# - name: apiAppAPIMName
#   default: ''
# - name: azureSubscription
#   default: ''
# - name: organizationName
#   default: ''
# - name: region
#   default: ''
# - name: resourceGroupName
#   default: ''
# - name: webAPIScope
#   default: ''
# - name: webAPIUrl
#   default: ''
# - name: webAppName
#   default: ''


stages:
# ------------------------------------------------------------------------------------------------------------------------
- stage: BuildApps
  displayName: Build Apps (${{ parameters.buildDeployApps }})
  jobs:

  - ${{ if or(or(eq(lower(parameters.runDevSecOpsScan), 'true'), eq(lower(parameters.runPsRuleScan), 'true')), eq(lower(parameters.runGHAzDOScan), 'true')) }}:
    - template: templates/scan-code-template.yml
      parameters:
        environmentName: 'DEV'
        runDevSecOpsScan: ${{ parameters.runDevSecOpsScan }}
        runPsRuleScan: ${{ parameters.runPsRuleScan }}
        runGHAzDOScan: ${{ parameters.runGHAzDOScan }}
        workingDirectoryCode: ${{ parameters.workingDirectoryCode }}
        workingDirectoryInfra: ${{ parameters.workingDirectoryInfra }}

  - template: templates/build-webapi-template.yml
    parameters:
      buildDeployApps: ${{ parameters.buildDeployApps }}
      buildConfiguration: 'Release'
      rootDirectory: ${{ parameters.apiSourcePath }}
      artifactName: ${{ parameters.apiArtifactName }} 

  - template: templates/build-webapp-template.yml
    parameters:
      buildDeployApps: ${{ parameters.buildDeployApps }}
      buildConfiguration: 'Release'
      rootDirectory: ${{ parameters.webSourcePath }}
      artifactName: ${{ parameters.webArtifactName }}

# ------------------------------------------------------------------------------------------------------------------------
- stage: CreateAzureInfra
  displayName: Create Infra (${{ parameters.createInfra }})
  dependsOn: BuildApps
  condition: succeeded('BuildApps')
  jobs:
  - template: templates/create-infra-vg-template.yml
    parameters:
      variableGroupName: ${{ parameters.variableGroupName }}
      createInfra: ${{ parameters.createInfra }}
      # From VG
      #adminEmail:  ${{ parameters.adminEmail }}
      #adDomain:  ${{ parameters.adDomain }}
      #adTenantId:  ${{ parameters.adTenantId }}
      #adClientId:  ${{ parameters.adClientId }}
      #apiAppAPIMName:  ${{ parameters.apiAppAPIMName }}
      #apiAppName:  ${{ parameters.apiAppName }}
      #azureSubscription: ${{ parameters.azureSubscription }}
      #organizationName:  ${{ parameters.organizationName }}
      #region: ${{ parameters.region }}
      #resourceGroupName:  ${{ parameters.resourceGroupName }}
      #webAPIScope:  ${{ parameters.webAPIScope }}
      #webAPIUrl:  ${{ parameters.webAPIUrl }}
      #webAppName:  ${{ parameters.webAppName }}

# ------------------------------------------------------------------------------------------------------------------------
- stage: DeployApp
  displayName: Deploy App (${{ parameters.buildDeployApps }})
  dependsOn: CreateAzureInfra
  condition: succeeded('CreateAzureInfra')
  jobs:
  - template: templates/deploy-apps-vg-template.yml
    parameters:
      variableGroupName: ${{ parameters.variableGroupName }}
      buildDeployApps: ${{ parameters.buildDeployApps }}
      webPackageName: ${{ parameters.webPackageName }}
      apiPackageName: ${{ parameters.apiPackageName }}
      webArtifactName: ${{ parameters.webArtifactName }}
      apiArtifactName: ${{ parameters.apiArtifactName }} 
      # From VG
      #azureSubscription: ${{ parameters.azureSubscription }}
      #webAppName:  ${{ parameters.webAppName }}
      #apiAppName:  ${{ parameters.apiAppName }}
