# ------------------------------------------------------------------------------------------------------------------------
# Pipe Template to run a Playwright test
# ------------------------------------------------------------------------------------------------------------------------
parameters:
- name: pwVariableGroupName
  default: ''
- name: pwKVGroupName
  default: ''
- name: pwScriptPath
  default: ''

stages:
# ------------------------------------------------------------------------------------------------------------------------
- stage: SmokeTestApp
  displayName: Smoke Test App (${{ parameters.environment }})
  jobs:
  - template: templates/playwright-template.yml
    parameters:
      pwVariableGroupName: ${{ parameters.pwVariableGroupName }}
      pwKVGroupName: ${{ parameters.pwKVGroupName }}
      pwScriptPath: ${{ parameters.pwScriptPath }}
