parameters: 
- name: stageName
  default: ''
- name: environment
  default: ''
- name: azureSubscription
  default: ''
- name: apiAppName
  default: ''
- name: organizationName
  default: 'scrutz'
- name: adminEmail
  default: 'scrutz@microsoft.com'
- name: resourceGroupName
  default: ''
- name: storageAccountName
  default: ''
- name: region
  default: ''
- name: packageName
  default: ''  


stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageName }}

    jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: ${{ parameters.environment }}
      pool:
        vmImage: 'vs2017-win2016'
  
      strategy:
        runOnce:
          deploy:
  
            steps:
            - task: AzureResourceGroupDeployment@2
              displayName: '1. Create APIM'
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                resourceGroupName: ${{ parameters.resourceGroupName }}
                location: ${{ parameters.region }}
                csmFile: '$(Pipeline.Workspace)/build/Infrastructure/api-management-consumption.json'
                overrideParameters: '-apimName ${{ parameters.apiAppName }} -organizationName ${{ parameters.organizationName }} -adminEmail ${{ parameters.adminEmail }}'
                deploymentOutputs: ResourceGroupDeploymentOutputs

            - task: AzureResourceGroupDeployment@2
              displayName: '2. Create App Service'
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                resourceGroupName: ${{ parameters.resourceGroupName }}
                location: ${{ parameters.region }}
                csmFile: '$(Pipeline.Workspace)/build/Infrastructure/appservice-web-app.json'
                overrideParameters: '-appName ${{ parameters.apiAppName }}'
                deploymentOutputs: ResourceGroupDeploymentOutputs

            - task: AzureRmWebAppDeployment@4
              displayName: '3. Application Deployment'
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                WebAppName: ${{ parameters.apiAppName }}
                package: '$(Pipeline.Workspace)/build/App/${{ parameters.packageName }}'
                AppSettings: ''